apiVersion: v1
kind: Service
metadata:
  name: kafka1
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-dns-label-name: kafka1
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: crs-kafka-1
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
