[source_db]
host = "127.0.0.1"
port = 3306
user = "testuser"
password = "testpassword"
db = "testdb"

[target_db]
host = "127.0.0.1"
port = 4000
user = "testuser"
password = "testpassword"
db = "testdb"

[lambdavpc]
vpcid = "vpc_id"
security_group_id = "security_group_id"
subnets = [ "subnet001", "subnet002" ]

[bucket_info]
bucket_name = "bucket_name"
s3key = "data"
